Adding support for replicaSets in pyramid-mongoengine
marioidival/pyramid_mongoengine pull request #5
Opened 2020-01-26 20:32 UTC by theclimber

Please find below the code slightly adapted in order to support a replicaSet cluster of mongoDB databases

2020-01-27 13:47 UTC, marioidival requested changes

2020-01-27 13:47 UTC, marioidival commented on pyramid_mongoengine/__init__.py
> +    #      \t{mongodb_rs}""")
Can you remove this comment please?

2020-02-10 22:43 UTC, theclimber commented on pyramid_mongoengine/__init__.py
> +    #      \t{mongodb_rs}""")
Done!

2020-02-11 12:24 UTC, marioidival approved these changes

2020-02-11 12:24 UTC, merged